title: Typography, Politics and You
description: An in-depth look into the relationships between different typefaces
  and their political connotations.
header_text: ""
footer_text: Copyright 2020 Ella Horrell
header_feature_image: ../uploads/img_1189.jpg
bannerheight: 40vmax
logo: ../uploads/unnamed.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
