title: Typography, Politics and You
description: An in-depth look into the relationships between different typefaces
  and their political connotations.
header_text: ""
footer_text: Copyright 2020 Ella Horrell
header_feature_image: ../uploads/img_1190.jpg
bannerheight: 20vmax
logo: ../uploads/favicon.png
favicon: ../uploads/favicon.png
gridlayout: false
fixednavbar: true
upzoom: true
