title: Typography, Politics and You
description: An in-depth look into the relationships between different typefaces
  and their political connotations.
header_text: ""
footer_text: Copyright 2020 Ella Horrell
header_feature_image: ../uploads/elliott-stallion-1uy8uuukids-unsplash.jpg
bannerheight: 10vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
